FROM openjdk:jre-slim
MAINTAINER XebiaLabs "info@xebialabs.com"

RUN apt-get update && \
    apt-get install -y supervisor wget && \
    rm -rf /var/lib/apt/lists/*

RUN wget --progress=dot:giga -O /tmp/xl-deploy-trial-server.zip https://dist.xebialabs.com/xl-deploy-trial-server.zip && \
    mkdir -p /opt/xld && \
    unzip /tmp/xl-deploy-trial-server.zip -d /opt/xld && \
    mv /opt/xld/xl-deploy-*-server /opt/xld/server && \
    rm -rf /tmp/xl-deploy-trial-server.zip

RUN wget --progress=dot:giga -O /tmp/xl-deploy-trial-cli.zip https://dist.xebialabs.com/xl-deploy-trial-cli.zip && \
    mkdir -p /opt/xld && \
    unzip /tmp/xl-deploy-trial-cli.zip -d /opt/xld && \
    mv /opt/xld/xl-deploy-*-cli /opt/xld/cli && \
    rm -rf /tmp/xl-deploy-trial-cli.zip

ADD resources/deployit.conf /opt/xld/server/conf/deployit.conf

RUN /opt/xld/server/bin/run.sh -setup -reinitialize -force \
    && ln -fs /license/deployit-license.lic /opt/xld/server/conf/deployit-license.lic

ADD resources/supervisord.conf /etc/supervisord.conf
CMD ["/usr/bin/supervisord"]

EXPOSE 4516
